version: "3.9"

services:
    web:
        build: .
        restart: on-failure:3
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        depends_on:
            - db
        environment:
            POSTGRES_HOST: db
            POSTGRES_PORT: 5432
            POSTGRES_DB: mydb
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password

    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: mydb

    nginx:
        image: nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - web
