version: "3.9"

services:
    web:
        build:
            context: ./project
        restart: on-failure:3
        depends_on:
            - db
        environment:
            POSTGRES_HOST: db
            POSTGRES_PORT: 5432
            POSTGRES_DB: mydb
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        command: >
            sh -c " python manage.py makemigrations &&
            python manage.py migrate &&
            gunicorn --bind 0.0.0.0:8000 project.wsgi:application"
        networks:
            - my_network

    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: mydb
        networks:
            - my_network

    nginx:
        image: nginx
        ports:
            - "443:443"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/certificates:/etc/nginx/certificates
        depends_on:
            - web
        networks:
            - my_network

networks:
    my_network: